export const FontFamily = {
  black: 'Roboto-Black',
  blackI: 'Roboto-BlackItalic',
  bold: 'Roboto-Bold',
  boldI: 'Roboto-BoldItalic',
  extraBold: 'Roboto-ExtraBold',
  extraBoldI: 'Roboto-ExtraBoldItalic',
  italic: 'Roboto-Italic',
  light: 'Roboto-Light',
  lightI: 'Roboto-LightItalic',
  medium: 'Roboto-Medium',
  mediumI: 'Roboto-MediumItalic',
  regular: 'Roboto-Regular',
  thin: 'Roboto-Thin',
  thinI: 'Roboto-ThinItalic',
  extraLight: 'Roboto-ExtraLight',
  extraLightI: 'Roboto-ExtraLightItalic',
  semiBold: 'Roboto-SemiBold',
  semiBoldI: 'Roboto-SemiBoldItalic',
};
