export const FontFamily = {
  black: 'Gilroy-Black',
  blackI: 'Gilroy-BlackItalic',
  bold: 'Gilroy-Bold',
  boldI: 'Gilroy-BoldItalic',
  extraBold: 'Gilroy-ExtraBold',
  extraBoldI: 'Gilroy-ExtraBoldItalic',
  heavy: 'Gilroy-Heavy',
  heavyI: 'Gilroy-HeavyItalic',
  light: 'Gilroy-Light',
  lightI: 'Gilroy-LightItalic',
  medium: 'Gilroy-Medium',
  mediumI: 'Gilroy-MediumItalic',
  regular: 'Gilroy-Regular',
  regularI: 'Gilroy-RegularItalic',
  thin: 'Gilroy-Thin',
  thinI: 'Gilroy-ThinItalic',
  extraLight: 'Gilroy-UltraLight',
  extraLightI: 'Gilroy-UltraLightItalic',
  semiBold: 'Gilroy-SemiBold',
  semiBoldI: 'Gilroy-SemiBoldItalic',
};
